In [1]:
import numpy as np

In [7]:
list_data = [1, 2, 3]
array = np.array(list_data)   #배열을 array() 안에 넣으면 행렬로 변환됨
array

array([1, 2, 3])

In [10]:
print(array.size)   # size는 원소의 갯수.  shape는 차원. (2,1) 이런식
print(array.dtype)

3
int32


In [11]:
array[2] #list와 마찬가지로 해당 인덱스로도 가져올 수 있음

3

In [17]:
array1 = np.arange(4)   # 0<=  <4 까지 정수를 집어넣겠다
print(array1)
array1

[0 1 2 3]


array([0, 1, 2, 3])

In [23]:
array2 = np.zeros((4,4), dtype = float)

In [24]:
array2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
array3 = np.ones((3, 3), dtype = str)

In [32]:
array3

array([['1', '1', '1'],
       ['1', '1', '1'],
       ['1', '1', '1']], dtype='<U1')

In [37]:
# 0부터 9까지 랜덤하게 초기화된 배열 만들기

In [38]:
array4 = np.random.randint(  0, 10, (3, 3)  )   # 0 <= x < 10 중 3행3열로 랜덤으로 

In [39]:
array4

array([[7, 9, 8],
       [8, 3, 0],
       [0, 3, 2]])

In [41]:
# 평균 0, 표준편차가 1인 표준정규분표를 띄는 3X3 배열 만들기

In [85]:
array5 = np.random.normal(   0, 1, (3, 3)   )

In [86]:
array5

array([[ 0.28086134, -0.92097427,  0.94897102],
       [ 0.54987788,  0.73239353, -1.1946853 ],
       [ 0.664437  , -0.014584  , -0.41574398]])


배열 합치기 (같은 dimension끼리만 가능) (concatenate())

In [51]:
array1 = np.array( [1, 2, 3] )

In [52]:
array2 = np.array( [4, 5, 6] )

In [54]:
array3 = np.concatenate( [array1, array2] )   # array([1, 2, 3, 4, 5, 6])

In [55]:
array3

array([1, 2, 3, 4, 5, 6])

In [56]:
array3.shape

(6,)

배열 바꾸기 (reshape)

In [57]:
array1= np.array( [1, 2, 3, 4] )

In [58]:
array2 = array1.reshape( (2, 2) )

In [59]:
array2

array([[1, 2],
       [3, 4]])

In [60]:
array1 = np.arange(4).reshape(1, 4)

In [61]:
array1

array([[0, 1, 2, 3]])

In [62]:
array2 = np.arange(8).reshape(2, 4)

In [63]:
array2

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [67]:
array3 = np.concatenate( [array1, array2] , axis = 0)   # 행렬 세로로 합치기

In [68]:
array3

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [4, 5, 6, 7]])

배열 나누기(split)

In [69]:
array = np.arange(8).reshape(2, 4)

In [77]:
left, right = np.split(array, [2], axis = 1)  # axis = 1 이면 열(세로)로. 즉, 3번째 열을 기준으로 쪼갠다

In [78]:
array

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [79]:
left

array([[0, 1],
       [4, 5]])

In [80]:
right

array([[2, 3],
       [6, 7]])

In [81]:
left.shape

(2, 2)

In [82]:
right.shape

(2, 2)

# Numpy의 연산과 함수

In [87]:
array = np.random.randint(1, 10, size=4).reshape(2, 2)
result_array = array * 10
print(result_array)

[[30 10]
 [30 90]]


In [88]:
array1 = np.arange(4).reshape(2, 2)
array2 = np.arange(2)
array3 = array1 + array2

print(array3)

[[0 2]
 [2 4]]


In [95]:
array1 = np.arange(0, 8).reshape(2, 4)
array2 = np.arange(0, 8).reshape(2, 4)
array3 = np.concatenate([array1, array2], axis=0)
array4 = np.arange(0, 4).reshape(4,1)
print(array3)
print(array4)
print(array3 + array4)

[[0 1 2 3]
 [4 5 6 7]
 [0 1 2 3]
 [4 5 6 7]]
[[0]
 [1]
 [2]
 [3]]
[[ 0  1  2  3]
 [ 5  6  7  8]
 [ 2  3  4  5]
 [ 7  8  9 10]]


### 마스킹 연산 (각 원소를 체크하는 것)

In [97]:
array1 = np.arange(16).reshape(4, 4)
print(array1)

array2 = array1 < 10
print(array2)

array1[array2] = 100   # array1행렬의 원소들 중에 마스킹된 array2조건을 만족하는 애들만 (즉 true인 애들만) 100으로 바꾸겠다 
print(array1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True False False]
 [False False False False]]
[[100 100 100 100]
 [100 100 100 100]
 [100 100  10  11]
 [ 12  13  14  15]]


### 집계 함수

In [98]:
array = np.arange(16).reshape(4, 4)

print("최대값:", np.max(array))
print("최소값:", np.min(array))
print("합계:", np.sum(array))
print("평균값:", np.mean(array))

최대값: 15
최소값: 0
합계: 120
평균값: 7.5


In [99]:
array = np.arange(16).reshape(4, 4)

print(array)
print("합계:", np.sum(array, axis=0))  #열에 대해서만 합계 구하기

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
합계: [24 28 32 36]
