In [1]:
%config Completer.use_jedi = False

In [2]:
import numpy as np

In [3]:
a = np.arange(21) # 21개 만듦

In [4]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [5]:
b = a.reshape(3,7)   # 3행 7열 행렬 만듦

In [6]:
b

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20]])

In [7]:
a.shape # 1행 21열

(21,)

In [8]:
b.shape # 3행 7열

(3, 7)

In [9]:
a.ndim

1

In [10]:
b.ndim # 차원 수 2

2

In [11]:
a.dtype.name

'int32'

In [12]:
type(a)

numpy.ndarray

In [13]:
c = np.array( [ (1,2,3), (4, 5.5, 6) ] )

In [14]:
c     # 소수점 하나 들어가니까 자동으로 다 float으로 바뀌게 됨

array([[1. , 2. , 3. ],
       [4. , 5.5, 6. ]])

In [15]:
c.dtype   # 소수점 하나 들어가니까 자동으로 다 float으로 바뀌게 됨

dtype('float64')

In [16]:
d = np.array( [ (1, 2, 3), (4, 5.5, 6) ], dtype = int )    # 타입을 int로 바꿈

In [17]:
d

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
np.zeros( (3, 5) ) 

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
np.ones( (3, 5) )                 

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
np.full( (3,3), 777.7 )

array([[777.7, 777.7, 777.7],
       [777.7, 777.7, 777.7],
       [777.7, 777.7, 777.7]])

In [21]:
np.arange(1, 20, 2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [22]:
np.arange(1, 20, 1.9)

array([ 1. ,  2.9,  4.8,  6.7,  8.6, 10.5, 12.4, 14.3, 16.2, 18.1])

In [23]:
np.linspace(0, 10, 11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [24]:
np.linspace(0, 10, 11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [34]:
np.linspace(0, 10, 4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [37]:
e = np.array( [1, 2, 3, 4] )
e

array([1, 2, 3, 4])

In [36]:
f = np.arange(4)
f

array([0, 1, 2, 3])

In [38]:
e*f

array([ 0,  2,  6, 12])

In [39]:
e-f

array([1, 1, 1, 1])

In [40]:
e**3 #3제곱

array([ 1,  8, 27, 64], dtype=int32)