In [1]:
import numpy as np

# Numpy의 활용

### 단일 객체 저장 및 불러오기

In [2]:
array = np.arange(0, 10)
np.save('saved.npy', array)  # 저장

result = np.load('saved.npy')  # 불러오기
print(result)

[0 1 2 3 4 5 6 7 8 9]


### 복수 객체 저장 및 불러오기

In [3]:
array1 = np.arange(0, 10)
array2 = np.arange(10, 20)
np.savez('saved.npz', array1=array1, array2=array2)  # 저장

data = np.load('saved.npz')   # 불러오기
result1 = data['array1']
result2 = data['array2']
print(result1)
print(result2)

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]


### 정렬

In [18]:
# Numpy 원소 오름차순 정렬
array = np.array([5, 9, 10, 3, 1])
array.sort()
print(array,"\n")

# Numpy 원소 내림차순 정렬
array = np.array([5, 9, 10, 3, 1])
array.sort()
print(array[::-1],"\n")

# 각 열을 기준으로 정렬
array = np.array([[5, 9, 10, 3, 1], [8, 3, 4, 2, 5]])
print(array,"\n")
array.sort(axis=0) # 기준이 행(axis=0). 만약 axis=1이면 열이 기준.
print(array) # 큰 애들이 아래 행으로 다 내려옴. (위의 행부터 오름차순 정렬)

[ 1  3  5  9 10] 

[10  9  5  3  1] 

[[ 5  9 10  3  1]
 [ 8  3  4  2  5]] 

[[ 5  3  4  2  1]
 [ 8  9 10  3  5]]


### Numpy 관련 자주 사용되는 함수

In [32]:
# 균일한 간격으로 데이터 생성
array = np.linspace(0, 10, 5)
print(array ,"\n")

# 난수의 재연(실행마다 결과 동일)
np.random.seed(8)  # seed안에 숫자만 안바뀌면 난수도 바뀌지 않음
print(np.random.randint(0, 10, (2, 3)))

[ 0.   2.5  5.   7.5 10. ] 

[[3 4 1]
 [9 5 8]]


In [31]:
# Numpy 배열 객체 복사
array1 = np.arange(0, 10)
array2 = array1.copy() # copy() 안하고 그냥 array2 = array1으로 하면 주소가 동일하기 때문에 array2를 바꾸면 원본인 array1도 같이 바뀜
print(array2 ,"\n")

# 중복된 원소 제거
array = np.array([1, 1, 2, 3, 3, 3, 1])
print(np.unique(array))

[0 1 2 3 4 5 6 7 8 9] 

[1 2 3]
